name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch name'
        required: true
      target_branch:
        description: 'Target branch name'
        required: true

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.source_branch }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: new-branch
          base: ${{ github.event.inputs.target_branch }}
          title: 'Automated Pull Request'
          body: 'This pull request was automatically created.'
